// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuX5N9axVD6_olpjP2rb_7xVxYloHdugA',
    appId: '1:375973688093:web:adb3167959859cede9a7f4',
    messagingSenderId: '375973688093',
    projectId: 'first-app-46e07',
    authDomain: 'first-app-46e07.firebaseapp.com',
    databaseURL: 'https://first-app-46e07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-46e07.firebasestorage.app',
    measurementId: 'G-V223E2QCR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJvnqAq9gPsCNoTyOeQH5LjoDXFnbrMg',
    appId: '1:375973688093:android:bd25100027547e81e9a7f4',
    messagingSenderId: '375973688093',
    projectId: 'first-app-46e07',
    databaseURL: 'https://first-app-46e07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-46e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLuvJSHtU_Xnt22iVz4OCwUkEuNjSoG8',
    appId: '1:375973688093:ios:230b25afa6d91f7de9a7f4',
    messagingSenderId: '375973688093',
    projectId: 'first-app-46e07',
    databaseURL: 'https://first-app-46e07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-46e07.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeLuvJSHtU_Xnt22iVz4OCwUkEuNjSoG8',
    appId: '1:375973688093:ios:230b25afa6d91f7de9a7f4',
    messagingSenderId: '375973688093',
    projectId: 'first-app-46e07',
    databaseURL: 'https://first-app-46e07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-46e07.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuX5N9axVD6_olpjP2rb_7xVxYloHdugA',
    appId: '1:375973688093:web:ac63cc171f9549cae9a7f4',
    messagingSenderId: '375973688093',
    projectId: 'first-app-46e07',
    authDomain: 'first-app-46e07.firebaseapp.com',
    databaseURL: 'https://first-app-46e07-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-46e07.firebasestorage.app',
    measurementId: 'G-EXBPVN93KD',
  );
}
